[service]
port = 5052
location = "ss"

[database]
dbType = "mysql"
username = "root"
password = "123456"
url = "(localhost:3306)/tenant"
maxOpenConns = 10
maxIdleConns = 5

[log]
path = "./logs/app.log"
